### ISSUE TITLE
Showing count of test cases double than actually written in code, and showing code coverage summary twice..!!

### ISSUE THREAD

**Issue by chintuboy** [gdi2290/angular-starter#1994] opened 2018-03-19 12:14 UTC
It is showing test cases count double than actual count of test which are written in code, I wrote two test cases in "app.component.spec.ts" and when I run "npm test", it executes successfully but shows like "√ 4 tests completed" and "TOTAL: 4 SUCCESS" rather than 2, and same for code coverage, It shows code coverage summary twice..!!

 
![image](https://user-images.githubusercontent.com/30890117/37595008-2624bee4-2b9d-11e8-93b7-9f7e2892ee0f.png)

Here we can see that I wrote only two test cases..!! then why it is showing 4..? ans same for code coverage..!! it is showing summery twice..!!

**Comment by sandip76** [comment] 2018-03-19 12:21
Facing the same issue!
Anyone, please help me on this issue

**Comment by lanovoy** [comment] 2018-03-19 15:06
Reproducible with current repo. Looks like karma is running the tests twice.
This might give some clues https://medium.com/@SchizoDuckie/so-your-karma-tests-run-twice-this-is-what-you-need-to-do-be74ce9f257e

**Comment by lanovoy** [comment] 2018-03-19 16:54
Pushed a fix. Basically, the browsers collection should only list one browser to be run.

**Comment by chintuboy** [comment] 2018-03-20 05:32
@lanovoy I have tried what you have changed in #1196, After that problem is resolved but on "npm test" browser was not started..!! It executes on terminal only..!! It is ok..?

**Comment by lanovoy** [comment] 2018-03-20 06:50
It uses Chrome headless mode.

вт, 20 марта 2018 г., 6:32 chintuboy <notifications@github.com>:

**Closed** 2018-03-20 16:10 UTC
Labels: bug
